services:
  echo-http:
    image: ghcr.io/probitas-test/echo-http:latest
    build: ./echo-http
    ports:
      - "18080:80"

  echo-grpc:
    image: ghcr.io/probitas-test/echo-grpc:latest
    build: ./echo-grpc
    ports:
      - "50051:50051"

  echo-graphql:
    image: ghcr.io/probitas-test/echo-graphql:latest
    build: ./echo-graphql
    ports:
      - "14000:8080"

  echo-connectrpc:
    image: ghcr.io/probitas-test/echo-connectrpc:latest
    build: ./echo-connectrpc
    ports:
      - "18081:8080"
