name: Build echo-http

on:
  push:
    branches: [main]
    paths:
      - "echo-http/**"
      - "flake.*"
      - ".github/workflows/build.echo-http.yml"
  pull_request:
    branches: [main]
    paths:
      - "echo-http/**"
      - "flake.*"
      - ".github/workflows/build.echo-http.yml"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: nixbuild/nix-quick-install-action@v34
      - run: nix develop -c just echo-http::lint
      - run: nix develop -c just echo-http::fmt
      - run: git diff --exit-code

  test:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: nixbuild/nix-quick-install-action@v34
      - run: nix develop -c just echo-http::test

  build:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: nixbuild/nix-quick-install-action@v34
      - run: nix develop -c just echo-http::build
