name: Build echo-graphql

on:
  push:
    branches: [main]
    paths:
      - "echo-graphql/**"
      - "flake.*"
      - ".github/workflows/build.echo-graphql.yml"
  pull_request:
    branches: [main]
    paths:
      - "echo-graphql/**"
      - "flake.*"
      - ".github/workflows/build.echo-graphql.yml"

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@v6
      - uses: nixbuild/nix-quick-install-action@v34
      - run: nix develop -c just echo-graphql::lint
      - run: nix develop -c just echo-graphql::fmt
      - run: git diff --exit-code

  test:
    needs: check
    runs-on: ubuntu-latest
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@v6
      - uses: nixbuild/nix-quick-install-action@v34
      - run: nix develop -c just echo-graphql::test

  build:
    needs: check
    runs-on: ubuntu-latest
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@v6
      - uses: nixbuild/nix-quick-install-action@v34
      - run: nix develop -c just echo-graphql::build
